[Service]
SyslogIdentifier=collectd
RuntimeDirectory=collectd
ExecStartPre=/bin/bash /usr/share/stat1090/scripts/readback.sh
ExecStartPre=/usr/sbin/collectd -t
ExecStopPost=/bin/bash /usr/share/stat1090/scripts/writeback.sh
Restart=always
RestartSec=10
